package Controls;

import Model.Blocks.IndestructableBlock;
import Model.Blocks.RegularBlock;
import Model.Enemies.BasicEnemy;
import Tools.Events.EventBus;
import Tools.Image.ImageFactory;
import Tools.Image.Boundaries.BoundariesFactoryLevel3;


public class Level3 extends GameLevel {

    public Level3(Screen screen) {
        super(screen);
    }

    public void begin() {
        this.setImageFactory(
            new ImageFactory(
                new BoundariesFactoryLevel3()
            )
        );
        super.begin();
    }

    public void draw() {
        RegularBlock block;
        IndestructableBlock wall;
        BasicEnemy enemy;
        //wall = new IndestructableBlock(0, 0);
        //enemy = new BasicEnemy(0, 0);
        //block = new RegularBlock(0, 0);
        //EventBus.getInstance().emit("create-element", block);
        //block = new RegularBlock(0, 1);

        //Bordas do mapa
        wall = new IndestructableBlock(0, 0);
        //início Lado esquedo
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 1);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 3);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 5);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 7);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 12);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 14);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 16);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 18);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(0, 19);
        // final lado esquerdo
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(1, 19);
        // início parte de baixo
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(3, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(5, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(7, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(9, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(12, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(14, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(16, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(18, 19);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 19);//final da parte de baixo
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(1, 0);
        //início do topo do mapa
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(3, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(5, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(7, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(9, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(12, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(14, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(16, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(18, 0);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 0);// final do topo do mapa
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 1);
        // início do lado direito do mapa
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 3);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 5);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 7);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 12);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 14);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 16);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(19, 18);
        //final lado direito
        EventBus.getInstance().emit("create-element", wall);
        //bordas do mapa
        //obstáculos do meio do mapa
        wall = new IndestructableBlock(2, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(2, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 7);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(4, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(5, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(5, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(6, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(7, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(7, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(8, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(9, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(9, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 16);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(10, 3);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(11, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(12, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(12, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(13, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(12, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(14, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(14, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 9);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 10);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(15, 17);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 2);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 4);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 6);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 8);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 11);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 13);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 15);
        EventBus.getInstance().emit("create-element", wall);
        wall = new IndestructableBlock(17, 17);
        EventBus.getInstance().emit("create-element", wall);

        //obstáculos do meio do mapa
        //destrutíveis do meio do mapa
        block = new RegularBlock(3, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(9, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(10, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 1);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(9, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(10, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 2);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(5, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(14, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 3);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(5, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(14, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 4);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(14, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 5);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(14, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 6);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(16, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 7);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 8);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 8);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 9);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 10);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 11);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 11);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 11);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 11);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 12);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 13);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 13);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 14);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 15);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 15);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(10, 15);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 15);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 15);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(7, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(9, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(12, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(13, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(15, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(16, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 16);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(8, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(9, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(10, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(11, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(16, 17);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(1, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(2, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(3, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(4, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(5, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(6, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(16, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(17, 18);
        EventBus.getInstance().emit("create-element", block);
        block = new RegularBlock(18, 18);
        EventBus.getInstance().emit("create-element", block);


        //destrutíveis do meio do mapa
        //inimigos
        enemy = new BasicEnemy(5, 1);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(15, 1);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(16, 4);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(3, 5);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(1, 12);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(3, 13);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(5, 10);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(9, 8);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(10, 11);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(11, 18);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(14, 9);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(16, 11);
        EventBus.getInstance().emit("create-enemy", enemy);
        enemy = new BasicEnemy(18, 11);
        EventBus.getInstance().emit("create-enemy", enemy);
        //inimigos


    }

}
